### Never send your "passwords" in Production ###

x-base: &common
  build:
    context: ./servEx
    dockerfile: Dockerfile
  restart: unless-stopped
  networks:
    - podman
  deploy:
    resources:
      limits:
        cpus: 2
        memory: 2048M
        pids: 200
  memswap_limit: 4096M
  logging:
    options:
      max-size: 10M
      max-file: 3
  security_opt:
    - no-new-privileges=true
  environment:
    - PUID=1000
    - PGID=1000

services:
  servEx-dev:
    <<: *common
    build:
      target: dev
    image: lipebol/servex-dev
    container_name: servEx-dev
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/servEx

networks:
  podman:
    external: true